import Link from 'next/link'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

const links = [
  { label: 'Home', route: '/' },
  { label: 'About', route: '/about' },
  { label: 'Post', route: '/post' }
]

export default function RootLayout ({ children }) {
  return (
    <html className='bg-black text-white' lang='en'>
      <body className={inter.className}>
        <header>
          <nav>
            <ul>
              {links.map(({ label, route }) => (
                <li key={route}>
                  <Link href={route}>
                    {label}
                  </Link>
                </li>
              ))}
            </ul>
          </nav>
        </header>
        {children}
      </body>
    </html>
  )
}
